spring.application.name=ai-resumopro
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-3.5-turbo


